name: liuhaotian/llava-v1.5-7b
model_name: "llava"
tokenizer_class: LlamaTokenizer
tokenizer_name: liuhaotian/llava-v1.5-7b
cache_dir: /root/autodl-tmp/model
cpu_copy: true
device: 0

# Methods
alg_name: "MEMIT"
stats_dir: "./data/stats"
layers: [7]
layer_selection: "all"
fact_token: "subject_last"
v_num_grad_steps: 25
v_lr: 5e-1
v_loss_layer: 31
v_weight_decay: 1e-3
kl_factor: 0.0625
clamp_norm_factor: 4
mom2_adjustment: false
mom2_update_weight: 15
# context_template_length_params: [[5, 10], [10, 10]]
context_template_length_params: [[5, 5]]

rewrite_module_tmp: "llava_model.model.layers.{}.mlp.down_proj"
layer_module_tmp: "llava_model.model.layers.{}"
mlp_module_tmp: "llava_model.model.layers.{}.mlp"
attn_module_tmp: "llava_model.model.layers.{}.self_attn"
ln_f_module: "llava_model.model.norm"
lm_head_module: "llava_model.lm_head"
mom2_dataset: "MMVQA"
# mom2_n_samples: 100000
mom2_n_samples: 1000
mom2_dtype: "float32"
model_parallel: false
fp16: false
batch_size: 2
# image
coco_image: /root/autodl-tmp/model_edit
rephrase_image: /root/autodl-tmp/model_edit
train_annotation_path: /root/autodl-tmp/model_edit/editing-data/vqa/vqa_train.json
eval_annotation_path: /root/autodl-tmp/model_edit/editing-data/vqa/vqa_eval.json
exact_match: True

# Trace
noise_level: s10
result_dir: /root/autodl-tmp/model_edit/results
all_metrics_name: 'all_metrics_layer=7.jsonl'
json_dir: /root/code/EasyEdit/results/jsonl

continuous_sample: 1
real_world_eval: true
api_key: "/root/autodl-tmp/api_key.json"

