# Model

name: liuhaotian/llava-v1.5-7b
model_name: llava
tokenizer_class: LlamaTokenizer
tokenizer_name: liuhaotian/llava-v1.5-7b
cache_dir: /home/lishichao/.cache/huggingface/hub/
device: 0,1

# Methods
alg_name: "AlphaEdit"
stats_dir: "./data/stats"
layers: [7]
layer_selection: "all"
fact_token: "subject_last"
specific_subject: false
v_num_grad_steps: 50
v_lr: 5e-1
v_loss_layer: 31
v_weight_decay: 1e-3
kl_factor: 0.0625
# clamp_norm_factor: 0.75
clamp_norm_factor: 4
mom2_adjustment: false
mom2_update_weight: 15000
P_loc: "/home/lishichao/project/EasyEdit/null_space_project.pt"

rewrite_module_tmp: "llava_model.model.layers.{}.mlp.down_proj"
layer_module_tmp: "llava_model.model.layers.{}"
mlp_module_tmp: "llava_model.model.layers.{}.mlp"
attn_module_tmp: "llava_model.model.layers.{}.self_attn"
ln_f_module: "llava_model.model.norm"
lm_head_module: "llava_model.lm_head"
# mom2_dataset: "wikipedia"
mom2_dataset: "MMVQA"
# mom2_n_samples: 100000
mom2_n_samples: 1000
mom2_dtype: "float32"
nullspace_threshold: 2e-2
L2: 1

model_parallel: false
fp16: false
batch_size: 2
# image
coco_image: /data/lishichao/data/model_edit/MMKE/data_image
rephrase_image: /data/lishichao/data/model_edit/MMKE/data_image
exact_match: True
train_annotation_path: /data/lishichao/data/model_edit/editing-data/vqa/vqa_train.json
eval_annotation_path: /data/lishichao/data/model_edit/MMKE/data_json/{}_eval.json
# exact_match: True
# Trace
noise_level: s10
result_dir: /data/lishichao/data/model_edit/results

# Evaluation
all_metrics_name: 'all_metrics_layer=7_cov1000.jsonl'
json_dir: /home/lishichao/project/EasyEdit/results/jsonl
continuous_sample: 1
real_world_eval: true
api_key: "/home/lishichao/project/api_key.json"