alg_name: "DPO"
name: liuhaotian/llava-v1.5-7b
model_name: "llava"
tokenizer_class: LlamaTokenizer
tokenizer_name: liuhaotian/llava-v1.5-7b
cache_dir: /home/lishichao/.cache/huggingface/hub/
device: 0,1

# Methods
lora_type: "adalora"
layers: []
num_steps: 7
batch_size: 2
max_length: 30
lr: 5e-5
weight_decay: 0
kl_factor: 0
rank: 8
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["q_proj", "v_proj"]  #["up_proj", "down_proj"] #["q_proj", "v_proj"]
model_parallel: False
alpha: 0.99
beta: 0.1
# image
coco_image: /data/lishichao/data/model_edit/
rephrase_image: /data/lishichao/data/model_edit/
result_dir: /data/lishichao/data/model_edit/results

# Evaluation
real_world_eval: true
api_key: "/home/lishichao/project/api_key.json"