# Model
device: 0
alg_name: "UNIKE"
name: liuhaotian/llava-v1.5-7b
model_name: llava
model_class: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: liuhaotian/llava-v1.5-7b
cache_dir: /home/wmq/.cache/huggingface/hub
inner_params: []

tp_layers:
  'llava_model.model.layers.31.mlp.gate_proj': 'output'
  'llava_model.model.layers.31.mlp.up_proj': 'output'
  'llava_model.model.layers.31.mlp.down_proj': 'input'

  'llava_model.model.layers.30.mlp.gate_proj': 'output'
  'llava_model.model.layers.30.mlp.up_proj': 'output'
  'llava_model.model.layers.30.mlp.down_proj': 'input'

  # 'llava_model.model.layers.29.mlp.gate_proj': 'output'
  # 'llava_model.model.layers.29.mlp.up_proj': 'output'
  # 'llava_model.model.layers.29.mlp.down_proj': 'input'

  # 'llava_model.model.layers.28.mlp.gate_proj': 'output'
  # 'llava_model.model.layers.28.mlp.up_proj': 'output'
  # 'llava_model.model.layers.28.mlp.down_proj': 'input'

l_ike_layers: 
- 'llava_model.model.layers.31.self_attn'
- 'llava_model.model.layers.30.self_attn'
# - 'llava_model.model.layers.29.self_attn'
# - 'llava_model.model.layers.28.self_attn'

beta: 0.9

# Method
alg: "UNIKE"
lr: 1e-6
edit_lr: 7e-4
lr_lr: 4e-4
lr_scale: 1.0
seed: 42
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
one_sided: False
n_hidden: 1
hidden_dim: 4096
init: id
norm: True
combine: True
x_only: False
delta_only: False
act: relu
rank: 1920
mlp_class: IDMLP
shared: True
archive: null

# Train
batch_size: 1
model_save_pt: 5000
silent: False
max_epochs: 100
max_iters: 50000
log_interval: 100
eval_log_interval: 1000
final_eval: True
val_interval: 5000
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
debug: False
save: False
verbose: True
max_norm: 1.1

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt_class: SGD
grad_clip: 100.

# Output
result_dir: /data/lishichao/data/model_edit/results

# Multimodal

# image
coco_image: /mnt/data2/wmq/
rephrase_image: /mnt/data2/wmq/
train_annotation_path: /mnt/data2/wmq/editing-data/vqa/vqa_train.json
eval_annotation_path: /mnt/data2/wmq/editing-data/vqa/vqa_eval.json

max_add_neuron_num: 25
freeze_model: True
freeze_k: 0
freeze_a: 0
memory_size: 40000
memory_loss: 'non_use'
amplify_v: 0
activate_loss: 'non_use'
act_margin_val: 0.0
margin_val1: 3
margin_val2: 3
hyperparams_nn: True
hyperparams_nn_count: 20


# Continue
continuous: True
continuous_sample: 1


# multi-task
multi_task: False

do_clip_norm: True
# max_epochs: 1

# Evaluation
real_world_eval: True
api_key: "/mnt/data2/wmq/api_key.json"


# ike
add_l_ike_layer: True