# Model
device: 0
alg_name: "UNIKE"
name: lmsys/vicuna-7b-v1.5
model_name: minigpt4
model_class: Blip2OPT
tokenizer_class: LlamaTokenizer
tokenizer_name: lmsys/vicuna-7b-v1.5
cache_dir: /home/wmq/.cache/huggingface/hub
inner_params: []

tp_layers:
  'llama_model.model.layers.31.mlp.gate_proj': 'output'
  'llama_model.model.layers.31.mlp.up_proj': 'output'
  'llama_model.model.layers.31.mlp.down_proj': 'input'

  'llama_model.model.layers.30.mlp.gate_proj': 'output'
  'llama_model.model.layers.30.mlp.up_proj': 'output'
  'llama_model.model.layers.30.mlp.down_proj': 'input'

  # 'llama_model.model.layers.29.mlp.gate_proj': 'output'
  # 'llama_model.model.layers.29.mlp.up_proj': 'output'
  # 'llama_model.model.layers.29.mlp.down_proj': 'input'

l_ike_layers: 
# - 'llama_model.model.layers.31.mlp_handler'
# - 'llama_model.model.layers.30.mlp'

beta: 0.9

# Method
alg: "UNIKE"
lr: 1e-6
edit_lr: 7e-4
lr_lr: 4e-4
lr_scale: 1.0
seed: 42
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
one_sided: False
n_hidden: 1
hidden_dim: null
init: id
norm: True
combine: True
x_only: False
delta_only: False
act: relu
rank: 1920
mlp_class: IDMLP
shared: True
archive: null

# Train
batch_size: 1
model_save_pt: 5000
silent: False
max_epochs: 10
max_iters: 50000
log_interval: 100
eval_log_interval: 1000
final_eval: True
val_interval: 5000
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
debug: False
save: False
verbose: True
max_norm: 1.1

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt_class: SGD
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: ./hugging_cache/minigpt4/blip2_pretrained_flant5xxl.pth
qformer_name_or_path: ./hugging_cache/bert-base-uncased
state_dict_file: ./hugging_cache/eva_vit_g.pth
pretrained_ckpt: ./hugging_cache/minigpt4/pretrained_minigpt4_7b.pth

# image
coco_image: ./images
rephrase_image: ./images



max_add_neuron_num: 25
freeze_model: True
freeze_k: 0
freeze_a: 0
memory_size: 40000
memory_loss: 'non_use'
amplify_v: 1
activate_loss: 'non_use'
act_margin_val: 0.0
margin_val1: 3
margin_val2: 3
hyperparams_nn: True
hyperparams_nn_count: 20


# Continue
continuous: True
continuous_sample: 1


# multi-task
multi_task: False

do_clip_norm: True
max_epochs: 1